name: flutter_ddd_firebase
description: Flutter Firebase & DDD
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  freezed_annotation: ^2.2.0
  flutter_bloc: ^8.1.2
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0
  google_sign_in: ^6.0.2
  get_it: ^7.2.0
  injectable: ^2.1.1
  another_flushbar: ^1.12.29
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^2.3.2
  build_runner: ^2.3.3
  injectable_generator: ^2.1.5

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
